import { AppState, Domain, Level, Term } from "./types";

export const APP_STATE_VERSION = 4;
export const APP_STATE_KEY = "it_supporter_state_v4";
export const LEGACY_APP_STATE_KEYS = ["it_supporter_state_v3"] as const;
export const APP_STATE_META_KEY = "it_supporter_state_v4_meta";
export const APP_STATE_PROGRESS_KEY = "it_supporter_state_v4_progress";
export const APP_STATE_PER_TERM_KEY = "it_supporter_state_v4_per_term";
export const APP_STATE_HISTORY_KEY = "it_supporter_state_v4_history";

export const DOMAIN_TREE: Record<Domain, string[]> = {
  ストラテジ系: [
    "企業活動",
    "法務",
    "経営戦略",
    "技術戦略",
    "ビジネスインダストリ",
    "システム概略",
    "システム企画",
  ],
  マネジメント系: [
    "システム開発技術",
    "ソフトウェア開発管理技術",
    "プロジェクトマネジメント",
    "サービスマネジメント",
    "システム監査",
  ],
  テクノロジ系: [
    "基礎理論",
    "アルゴリズムとプログラミング",
    "コンピュータ構成要素",
    "ソフトウェア",
    "ハードウェア",
    "情報デザイン",
    "情報メディア",
    "データベース",
    "ネットワーク",
    "セキュリティ",
  ],
};

export const TERMS: Term[] = [
  {
    id: "file",
    term: "ファイル",
    reading: "ふぁいる",
    level: "初級",
    domain: "テクノロジ系",
    category: "ソフトウェア",
    icon: "document-text-outline",
    easy: "データを保存するための入れ物です。",
    example: "レポートをファイルとして保存します。",
    workplace: "ファイル名を分かりやすくしてください。",
    translations: {
      en: "A file is a container for saved data.",
      zh: "文件是保存数据的容器。",
    },
    keywords: ["保存", "データ", "入れ物", "名前"],
    related: ["フォルダ", "拡張子"],
  },
  {
    id: "login",
    term: "ログイン",
    reading: "ろぐいん",
    level: "初級",
    domain: "ストラテジ系",
    category: "システム概略",
    icon: "log-in-outline",
    easy: "IDとパスワードを使って、サービスに入ることです。",
    example: "会社システムにログインして勤怠を入力します。",
    workplace: "ログインできない人の原因を調べます。",
    translations: {
      en: "Login means entering a service with ID and password.",
      zh: "登录是用账号和密码进入系统。",
    },
    keywords: ["ID", "パスワード", "入る", "認証"],
    related: ["認証", "アカウント"],
  },
  {
    id: "variable",
    term: "変数",
    reading: "へんすう",
    level: "初級",
    domain: "テクノロジ系",
    category: "アルゴリズムとプログラミング",
    icon: "cube-outline",
    easy: "データを入れておく箱です。",
    example: "ユーザー名を変数に入れて画面に表示します。",
    workplace: "この値は変数に入れて処理しましょう。",
    translations: {
      en: "A variable is a box for data.",
      zh: "变量是存放数据的盒子。",
    },
    keywords: ["箱", "データ", "値", "保存"],
    related: ["関数", "配列"],
  },
  {
    id: "api",
    term: "API",
    reading: "えーぴーあい",
    level: "中級",
    domain: "テクノロジ系",
    category: "ネットワーク",
    icon: "git-network-outline",
    easy: "アプリどうしが情報をやり取りするためのルールです。",
    example: "天気アプリは天気会社のAPIを使って情報を取得します。",
    workplace: "APIの接続テスト結果を共有してください。",
    translations: {
      en: "API is a rule for apps to exchange data.",
      zh: "API 是应用之间交换数据的规则。",
    },
    keywords: ["ルール", "情報", "やり取り", "接続"],
    related: ["Webhook", "SDK", "HTTP"],
  },
  {
    id: "database",
    term: "データベース",
    reading: "でーたべーす",
    level: "中級",
    domain: "テクノロジ系",
    category: "データベース",
    icon: "server-outline",
    easy: "データを整理して保存し、後で探せるようにする仕組みです。",
    example: "ユーザー情報をデータベースに保存します。",
    workplace: "データベースのバックアップを確認します。",
    translations: {
      en: "A database stores and organizes data.",
      zh: "数据库用于保存并整理数据。",
    },
    keywords: ["保存", "整理", "検索", "データ"],
    related: ["テーブル", "SQL", "正規化"],
  },
  {
    id: "normalization",
    term: "正規化",
    reading: "せいきか",
    level: "上級",
    domain: "テクノロジ系",
    category: "データベース",
    icon: "layers-outline",
    easy: "データの重複を減らして、管理しやすくする設計方法です。",
    example: "住所データを別テーブルに分けて正規化します。",
    workplace: "この設計は正規化しすぎていないか確認しましょう。",
    translations: {
      en: "Normalization reduces duplicate data structures.",
      zh: "规范化用于减少重复数据。",
    },
    keywords: ["重複", "データ", "整理", "テーブル"],
    related: ["データベース", "主キー", "外部キー"],
  },
  {
    id: "polymorphism",
    term: "ポリモーフィズム",
    reading: "ぽりもーふぃずむ",
    level: "上級",
    domain: "テクノロジ系",
    category: "ソフトウェア",
    icon: "shapes-outline",
    easy: "同じ名前の処理でも、型によって動きを変える考え方です。",
    example: "drawメソッドが図形ごとに違う動作をします。",
    workplace: "このクラス設計はポリモーフィズムで拡張できます。",
    translations: {
      en: "Polymorphism changes behavior by type.",
      zh: "多态会根据类型改变行为。",
    },
    keywords: ["同じ", "型", "動き", "処理"],
    related: ["継承", "インターフェース", "メソッド"],
  },
  {
    id: "kpi",
    term: "KPI",
    reading: "けーぴーあい",
    level: "中級",
    domain: "ストラテジ系",
    category: "経営戦略",
    icon: "speedometer-outline",
    easy: "目標がどれくらい達成できているかを測る数字です。",
    example: "問い合わせ対応時間をKPIとして毎週確認します。",
    workplace: "今月のKPIが未達なので改善案を出しましょう。",
    translations: {
      en: "KPI is a number to measure progress toward goals.",
      zh: "KPI 是衡量目标达成情况的指标。",
    },
    keywords: ["目標", "指標", "測定", "達成"],
    related: ["KGI", "PDCA", "目標管理"],
  },
  {
    id: "sla",
    term: "SLA",
    reading: "えすえるえー",
    level: "中級",
    domain: "ストラテジ系",
    category: "システム企画",
    icon: "document-outline",
    easy: "サービス提供者と利用者の間で決める品質の約束です。",
    example: "障害発生から2時間以内に一次回答するSLAを定義します。",
    workplace: "SLA違反が続いているので運用体制を見直します。",
    translations: {
      en: "SLA is an agreement about service quality.",
      zh: "SLA 是关于服务质量的约定。",
    },
    keywords: ["品質", "約束", "契約", "水準"],
    related: ["SLO", "サービスレベル", "運用"],
  },
  {
    id: "roi",
    term: "ROI",
    reading: "あーるおーあい",
    level: "中級",
    domain: "ストラテジ系",
    category: "企業活動",
    icon: "trending-up-outline",
    easy: "投資したお金に対して、どれだけ利益が出たかを示す割合です。",
    example: "新システム導入後のROIを半年ごとに評価します。",
    workplace: "ROIが低い施策は優先度を下げる判断が必要です。",
    translations: {
      en: "ROI shows the return on investment.",
      zh: "ROI 表示投资回报率。",
    },
    keywords: ["投資", "利益", "割合", "効果"],
    related: ["コスト", "利益率", "投資判断"],
  },
  {
    id: "benchmarking",
    term: "ベンチマーキング",
    reading: "べんちまーきんぐ",
    level: "上級",
    domain: "ストラテジ系",
    category: "ビジネスインダストリ",
    icon: "analytics-outline",
    easy: "他社や他部門の良い事例を比べて、自分たちの改善に生かす手法です。",
    example: "先進企業の運用指標をベンチマーキングして改善案を作成します。",
    workplace: "ベンチマーキング結果を来週の会議で共有してください。",
    translations: {
      en: "Benchmarking compares best practices to improve your work.",
      zh: "标杆分析是通过比较优秀案例来改进工作的方法。",
    },
    keywords: ["比較", "改善", "事例", "指標"],
    related: ["KPI", "業務改善", "分析"],
  },
  {
    id: "compliance",
    term: "コンプライアンス",
    reading: "こんぷらいあんす",
    level: "初級",
    domain: "ストラテジ系",
    category: "法務",
    icon: "shield-checkmark-outline",
    easy: "法律や社内ルールを守って業務を行うことです。",
    example: "個人情報の取り扱いはコンプライアンス研修で確認します。",
    workplace: "この手順はコンプライアンス上の確認が必要です。",
    translations: {
      en: "Compliance means following laws and rules.",
      zh: "合规是指遵守法律和规则。",
    },
    keywords: ["法律", "規則", "順守", "管理"],
    related: ["ガバナンス", "監査", "内部統制"],
  },
  {
    id: "wbs",
    term: "WBS",
    reading: "だぶりゅーびーえす",
    level: "中級",
    domain: "マネジメント系",
    category: "プロジェクトマネジメント",
    icon: "list-outline",
    easy: "プロジェクトの作業を細かく分けて整理した表です。",
    example: "開発工程をWBSに分解して担当者を割り当てます。",
    workplace: "WBSの遅れタスクを先にリカバリしましょう。",
    translations: {
      en: "WBS breaks a project into manageable tasks.",
      zh: "WBS 是把项目拆分成可管理任务的结构。",
    },
    keywords: ["作業分解", "計画", "管理", "タスク"],
    related: ["ガントチャート", "進捗", "工数"],
  },
  {
    id: "risk-management",
    term: "リスク管理",
    reading: "りすくかんり",
    level: "中級",
    domain: "マネジメント系",
    category: "プロジェクトマネジメント",
    icon: "warning-outline",
    easy: "問題が起きる前に危険を見つけて対策することです。",
    example: "要員不足のリスクに備えて外部要員を確保します。",
    workplace: "今週のリスク管理表を更新してください。",
    translations: {
      en: "Risk management identifies and handles potential problems.",
      zh: "风险管理是提前识别并应对潜在问题。",
    },
    keywords: ["危険", "対策", "予防", "管理"],
    related: ["課題管理", "品質管理", "変更管理"],
  },
  {
    id: "incident",
    term: "インシデント",
    reading: "いんしでんと",
    level: "初級",
    domain: "マネジメント系",
    category: "サービスマネジメント",
    icon: "alert-circle-outline",
    easy: "サービスの品質を下げる障害や問い合わせのことです。",
    example: "システム停止は重大インシデントとして記録します。",
    workplace: "インシデント対応履歴をチケットに残してください。",
    translations: {
      en: "An incident is an event that disrupts service quality.",
      zh: "事件是影响服务质量的故障或问题。",
    },
    keywords: ["障害", "対応", "記録", "品質"],
    related: ["問題管理", "エスカレーション", "SLA"],
  },
  {
    id: "change-management",
    term: "変更管理",
    reading: "へんこうかんり",
    level: "上級",
    domain: "マネジメント系",
    category: "ソフトウェア開発管理技術",
    icon: "git-compare-outline",
    easy: "システム変更の影響を確認し、安全に実施するための管理方法です。",
    example: "本番リリース前に変更管理会議で承認を取ります。",
    workplace: "緊急変更でも変更管理フローは省略しないでください。",
    translations: {
      en: "Change management controls system changes safely.",
      zh: "变更管理用于安全地控制系统变更。",
    },
    keywords: ["変更", "影響", "承認", "管理"],
    related: ["リリース", "構成管理", "インシデント"],
  },
  {
    id: "audit-log",
    term: "監査ログ",
    reading: "かんさろぐ",
    level: "中級",
    domain: "マネジメント系",
    category: "システム監査",
    icon: "reader-outline",
    easy: "誰がいつ何をしたかを後で確認できる記録です。",
    example: "操作履歴を監査ログとして1年間保存します。",
    workplace: "監査対応のため監査ログを提出してください。",
    translations: {
      en: "An audit log records who did what and when.",
      zh: "审计日志记录了谁在何时做了什么。",
    },
    keywords: ["記録", "履歴", "確認", "証跡"],
    related: ["アクセスログ", "監査", "セキュリティ"],
  },
  {
    id: "algorithm",
    term: "アルゴリズム",
    reading: "あるごりずむ",
    level: "初級",
    domain: "テクノロジ系",
    category: "アルゴリズムとプログラミング",
    icon: "git-branch-outline",
    easy: "問題を解くための手順やルールのことです。",
    example: "検索アルゴリズムを改善して処理を速くします。",
    workplace: "この処理のアルゴリズムを図で説明してください。",
    translations: {
      en: "An algorithm is a step-by-step procedure to solve a problem.",
      zh: "算法是解决问题的步骤和规则。",
    },
    keywords: ["手順", "ルール", "処理", "解決"],
    related: ["フローチャート", "擬似コード", "計算量"],
  },
  {
    id: "cache",
    term: "キャッシュ",
    reading: "きゃっしゅ",
    level: "初級",
    domain: "テクノロジ系",
    category: "ソフトウェア",
    icon: "flash-outline",
    easy: "よく使うデータを一時的に保存して、表示や処理を速くする仕組みです。",
    example: "画像をキャッシュして再表示を高速化します。",
    workplace: "キャッシュをクリアして最新データを確認してください。",
    translations: {
      en: "Cache stores frequently used data temporarily for speed.",
      zh: "缓存会临时保存常用数据以提升速度。",
    },
    keywords: ["一時保存", "高速化", "再利用", "データ"],
    related: ["メモリ", "CDN", "最適化"],
  },
  {
    id: "firewall",
    term: "ファイアウォール",
    reading: "ふぁいあうぉーる",
    level: "中級",
    domain: "テクノロジ系",
    category: "セキュリティ",
    icon: "shield-outline",
    easy: "不正な通信を止めて、ネットワークを守る仕組みです。",
    example: "外部からの不要なポート通信をファイアウォールで遮断します。",
    workplace: "新しい通信先を許可するためファイアウォール設定を更新します。",
    translations: {
      en: "A firewall blocks unauthorized network traffic.",
      zh: "防火墙用于阻止未授权的网络通信。",
    },
    keywords: ["通信", "遮断", "防御", "ネットワーク"],
    related: ["VPN", "IDS", "アクセス制御"],
  },
  {
    id: "encryption",
    term: "暗号化",
    reading: "あんごうか",
    level: "中級",
    domain: "テクノロジ系",
    category: "セキュリティ",
    icon: "lock-closed-outline",
    easy: "データを読めない形に変えて、第三者に見られないようにする技術です。",
    example: "通信内容をTLSで暗号化して送信します。",
    workplace: "個人情報ファイルは必ず暗号化して保管してください。",
    translations: {
      en: "Encryption converts data into unreadable form for protection.",
      zh: "加密会把数据转换为不可读形式来保护信息。",
    },
    keywords: ["保護", "変換", "通信", "安全"],
    related: ["復号", "鍵管理", "TLS"],
  },
  {
    id: "load-balancer",
    term: "ロードバランサ",
    reading: "ろーどばらんさ",
    level: "上級",
    domain: "テクノロジ系",
    category: "ネットワーク",
    icon: "swap-horizontal-outline",
    easy: "アクセスを複数サーバに分散して、止まりにくくする装置や仕組みです。",
    example: "ロードバランサでアクセスを2台のサーバに振り分けます。",
    workplace: "負荷増加に備えてロードバランサ設定を見直します。",
    translations: {
      en: "A load balancer distributes traffic across multiple servers.",
      zh: "负载均衡器会把流量分配到多个服务器。",
    },
    keywords: ["分散", "負荷", "可用性", "サーバ"],
    related: ["冗長化", "スケーリング", "可用性"],
  },
  {
    id: "kgi",
    term: "KGI",
    reading: "けーじーあい",
    level: "中級",
    domain: "ストラテジ系",
    category: "経営戦略",
    icon: "flag-outline",
    easy: "最終的に達成したい目標を表す指標です。",
    example: "売上目標をKGIとして設定し、毎月進捗を確認します。",
    workplace: "KGIに対して今の施策が有効か見直しましょう。",
    translations: {
      en: "KGI is an indicator of the final business goal.",
      zh: "KGI 是最终目标的关键指标。",
    },
    keywords: ["最終目標", "指標", "成果", "達成"],
    related: ["KPI", "目標管理", "戦略"],
  },
  {
    id: "bcp",
    term: "BCP",
    reading: "びーしーぴー",
    level: "上級",
    domain: "ストラテジ系",
    category: "企業活動",
    icon: "shield-half-outline",
    easy: "災害や障害が起きても事業を続けるための計画です。",
    example: "地震発生時のBCP手順を年1回訓練します。",
    workplace: "拠点停止を想定したBCPの更新が必要です。",
    translations: {
      en: "BCP is a plan to continue business during disruptions.",
      zh: "BCP 是在突发事件中维持业务的计划。",
    },
    keywords: ["継続", "災害", "計画", "復旧"],
    related: ["DR", "リスク管理", "運用"],
  },
  {
    id: "governance",
    term: "ガバナンス",
    reading: "がばなんす",
    level: "中級",
    domain: "ストラテジ系",
    category: "企業活動",
    icon: "people-outline",
    easy: "組織がルールに沿って正しく運営されるように管理することです。",
    example: "ITガバナンス体制を整え、承認フローを明確にします。",
    workplace: "ガバナンス強化のため権限管理を見直します。",
    translations: {
      en: "Governance ensures an organization is managed properly.",
      zh: "治理是确保组织按规则正确运行。",
    },
    keywords: ["統制", "運営", "ルール", "管理"],
    related: ["コンプライアンス", "内部統制", "監査"],
  },
  {
    id: "dx",
    term: "DX",
    reading: "でぃーえっくす",
    level: "初級",
    domain: "ストラテジ系",
    category: "技術戦略",
    icon: "rocket-outline",
    easy: "デジタル技術で業務やサービスの形を大きく変える取り組みです。",
    example: "紙申請をオンライン化してDXを進めます。",
    workplace: "DXの効果を測る指標を決めましょう。",
    translations: {
      en: "DX transforms business using digital technology.",
      zh: "DX 是利用数字技术推动业务转型。",
    },
    keywords: ["デジタル", "変革", "業務", "改善"],
    related: ["クラウド", "業務改革", "KPI"],
  },
  {
    id: "outsourcing",
    term: "アウトソーシング",
    reading: "あうとそーしんぐ",
    level: "初級",
    domain: "ストラテジ系",
    category: "企業活動",
    icon: "people-circle-outline",
    easy: "業務の一部を外部の会社に委託することです。",
    example: "ヘルプデスク業務をアウトソーシングします。",
    workplace: "アウトソーシング先との契約条件を確認してください。",
    translations: {
      en: "Outsourcing means delegating work to external providers.",
      zh: "外包是把部分工作委托给外部公司。",
    },
    keywords: ["委託", "外部", "契約", "業務"],
    related: ["SLA", "調達", "コスト管理"],
  },
  {
    id: "rfi",
    term: "RFI",
    reading: "あーるえふあい",
    level: "上級",
    domain: "ストラテジ系",
    category: "システム企画",
    icon: "help-buoy-outline",
    easy: "提案依頼の前に、情報を集めるためにベンダへ送る質問書です。",
    example: "製品比較のためにRFIを各社へ配布します。",
    workplace: "RFI回答を整理して要件定義に反映しましょう。",
    translations: {
      en: "RFI is a request for information before formal proposals.",
      zh: "RFI 是在正式提案前收集信息的请求。",
    },
    keywords: ["情報収集", "質問", "ベンダ", "調達"],
    related: ["RFP", "要件定義", "ベンダ選定"],
  },
  {
    id: "gant-chart",
    term: "ガントチャート",
    reading: "がんとちゃーと",
    level: "初級",
    domain: "マネジメント系",
    category: "プロジェクトマネジメント",
    icon: "calendar-outline",
    easy: "作業の期間と順番を横棒で見える化した工程表です。",
    example: "開発計画をガントチャートで共有します。",
    workplace: "遅延タスクをガントチャート上で確認してください。",
    translations: {
      en: "A Gantt chart visualizes task schedules and order.",
      zh: "甘特图用于可视化任务时间与顺序。",
    },
    keywords: ["工程", "期間", "進捗", "計画"],
    related: ["WBS", "マイルストーン", "工数"],
  },
  {
    id: "milestone",
    term: "マイルストーン",
    reading: "まいるすとーん",
    level: "初級",
    domain: "マネジメント系",
    category: "プロジェクトマネジメント",
    icon: "navigate-circle-outline",
    easy: "プロジェクトの重要な通過点となる日付や成果物です。",
    example: "設計完了日をマイルストーンとして設定します。",
    workplace: "次のマイルストーンまでの遅れを報告してください。",
    translations: {
      en: "A milestone is an important checkpoint in a project.",
      zh: "里程碑是项目中的关键节点。",
    },
    keywords: ["通過点", "期限", "成果", "計画"],
    related: ["ガントチャート", "進捗管理", "WBS"],
  },
  {
    id: "quality-assurance",
    term: "品質保証",
    reading: "ひんしつほしょう",
    level: "中級",
    domain: "マネジメント系",
    category: "システム開発技術",
    icon: "checkmark-done-outline",
    easy: "製品やサービスの品質を一定水準で保つための活動です。",
    example: "品質保証としてレビューとテスト基準を設けます。",
    workplace: "品質保証の観点で受け入れ条件を確認しましょう。",
    translations: {
      en: "Quality assurance keeps product quality at a defined level.",
      zh: "质量保证用于维持既定质量水平。",
    },
    keywords: ["品質", "基準", "確認", "改善"],
    related: ["テスト", "レビュー", "品質管理"],
  },
  {
    id: "release-management",
    term: "リリース管理",
    reading: "りりーすかんり",
    level: "中級",
    domain: "マネジメント系",
    category: "ソフトウェア開発管理技術",
    icon: "cloud-upload-outline",
    easy: "新機能や修正を安全に本番環境へ反映するための管理です。",
    example: "リリース管理で作業手順とロールバック手順を用意します。",
    workplace: "今夜のリリース管理チェックリストを確認してください。",
    translations: {
      en: "Release management controls safe deployment to production.",
      zh: "发布管理用于安全地将变更上线。",
    },
    keywords: ["本番反映", "手順", "変更", "管理"],
    related: ["変更管理", "デプロイ", "障害対応"],
  },
  {
    id: "service-desk",
    term: "サービスデスク",
    reading: "さーびすですく",
    level: "初級",
    domain: "マネジメント系",
    category: "サービスマネジメント",
    icon: "headset-outline",
    easy: "利用者からの問い合わせを受けて対応する窓口です。",
    example: "パスワード再発行はサービスデスクが一次対応します。",
    workplace: "サービスデスクの対応件数を月次で分析します。",
    translations: {
      en: "A service desk is the support contact point for users.",
      zh: "服务台是面向用户的支持窗口。",
    },
    keywords: ["問い合わせ", "窓口", "対応", "利用者"],
    related: ["インシデント", "SLA", "運用"],
  },
  {
    id: "problem-management",
    term: "問題管理",
    reading: "もんだいかんり",
    level: "上級",
    domain: "マネジメント系",
    category: "サービスマネジメント",
    icon: "search-outline",
    easy: "障害の根本原因を見つけて再発を防ぐための管理です。",
    example: "繰り返し発生する障害を問題管理で恒久対策します。",
    workplace: "問題管理チケットに原因分析結果を記載してください。",
    translations: {
      en: "Problem management finds root causes to prevent recurrence.",
      zh: "问题管理用于查明根因并防止再次发生。",
    },
    keywords: ["根本原因", "再発防止", "分析", "改善"],
    related: ["インシデント", "変更管理", "品質保証"],
  },
];

export const LEVEL_ORDER: Level[] = ["初級", "中級", "上級"];

export const initialState: AppState = {
  stateVersion: APP_STATE_VERSION,
  learnedCount: {},
  weakTerms: {},
  favorites: {},
  history: [],
  attempts: 0,
  correct: 0,
  studyMinutes: 0,
  streak: 0,
  lastStudyDate: "",
  dailyQuizDoneDate: "",
  lang: "ja",
  fontScale: 1,
};
