import { AppState, Domain, Level, Term } from "./types";

export const APP_STATE_KEY = "it_supporter_state_v3";

export const DOMAIN_TREE: Record<Domain, string[]> = {
  ストラテジ系: [
    "企業活動",
    "法務",
    "経営戦略",
    "技術戦略",
    "ビジネスインダストリ",
    "システム概略",
    "システム企画",
  ],
  マネジメント系: [
    "システム開発技術",
    "ソフトウェア開発管理技術",
    "プロジェクトマネジメント",
    "サービスマネジメント",
    "システム監査",
  ],
  テクノロジ系: [
    "基礎理論",
    "アルゴリズムとプログラミング",
    "コンピュータ構成要素",
    "ソフトウェア",
    "ハードウェア",
    "情報デザイン",
    "情報メディア",
    "データベース",
    "ネットワーク",
    "セキュリティ",
  ],
};

export const TERMS: Term[] = [
  {
    id: "file",
    term: "ファイル",
    reading: "ふぁいる",
    level: "初級",
    domain: "テクノロジ系",
    category: "ソフトウェア",
    icon: "document-text-outline",
    easy: "データを保存するための入れ物です。",
    example: "レポートをファイルとして保存します。",
    workplace: "ファイル名を分かりやすくしてください。",
    translations: {
      en: "A file is a container for saved data.",
      zh: "文件是保存数据的容器。",
    },
    keywords: ["保存", "データ", "入れ物", "名前"],
    related: ["フォルダ", "拡張子"],
  },
  {
    id: "login",
    term: "ログイン",
    reading: "ろぐいん",
    level: "初級",
    domain: "ストラテジ系",
    category: "システム概略",
    icon: "log-in-outline",
    easy: "IDとパスワードを使って、サービスに入ることです。",
    example: "会社システムにログインして勤怠を入力します。",
    workplace: "ログインできない人の原因を調べます。",
    translations: {
      en: "Login means entering a service with ID and password.",
      zh: "登录是用账号和密码进入系统。",
    },
    keywords: ["ID", "パスワード", "入る", "認証"],
    related: ["認証", "アカウント"],
  },
  {
    id: "variable",
    term: "変数",
    reading: "へんすう",
    level: "初級",
    domain: "テクノロジ系",
    category: "アルゴリズムとプログラミング",
    icon: "cube-outline",
    easy: "データを入れておく箱です。",
    example: "ユーザー名を変数に入れて画面に表示します。",
    workplace: "この値は変数に入れて処理しましょう。",
    translations: {
      en: "A variable is a box for data.",
      zh: "变量是存放数据的盒子。",
    },
    keywords: ["箱", "データ", "値", "保存"],
    related: ["関数", "配列"],
  },
  {
    id: "api",
    term: "API",
    reading: "えーぴーあい",
    level: "中級",
    domain: "テクノロジ系",
    category: "ネットワーク",
    icon: "git-network-outline",
    easy: "アプリどうしが情報をやり取りするためのルールです。",
    example: "天気アプリは天気会社のAPIを使って情報を取得します。",
    workplace: "APIの接続テスト結果を共有してください。",
    translations: {
      en: "API is a rule for apps to exchange data.",
      zh: "API 是应用之间交换数据的规则。",
    },
    keywords: ["ルール", "情報", "やり取り", "接続"],
    related: ["Webhook", "SDK", "HTTP"],
  },
  {
    id: "database",
    term: "データベース",
    reading: "でーたべーす",
    level: "中級",
    domain: "テクノロジ系",
    category: "データベース",
    icon: "server-outline",
    easy: "データを整理して保存し、後で探せるようにする仕組みです。",
    example: "ユーザー情報をデータベースに保存します。",
    workplace: "データベースのバックアップを確認します。",
    translations: {
      en: "A database stores and organizes data.",
      zh: "数据库用于保存并整理数据。",
    },
    keywords: ["保存", "整理", "検索", "データ"],
    related: ["テーブル", "SQL", "正規化"],
  },
  {
    id: "normalization",
    term: "正規化",
    reading: "せいきか",
    level: "上級",
    domain: "テクノロジ系",
    category: "データベース",
    icon: "layers-outline",
    easy: "データの重複を減らして、管理しやすくする設計方法です。",
    example: "住所データを別テーブルに分けて正規化します。",
    workplace: "この設計は正規化しすぎていないか確認しましょう。",
    translations: {
      en: "Normalization reduces duplicate data structures.",
      zh: "规范化用于减少重复数据。",
    },
    keywords: ["重複", "データ", "整理", "テーブル"],
    related: ["データベース", "主キー", "外部キー"],
  },
  {
    id: "polymorphism",
    term: "ポリモーフィズム",
    reading: "ぽりもーふぃずむ",
    level: "上級",
    domain: "テクノロジ系",
    category: "ソフトウェア",
    icon: "shapes-outline",
    easy: "同じ名前の処理でも、型によって動きを変える考え方です。",
    example: "drawメソッドが図形ごとに違う動作をします。",
    workplace: "このクラス設計はポリモーフィズムで拡張できます。",
    translations: {
      en: "Polymorphism changes behavior by type.",
      zh: "多态会根据类型改变行为。",
    },
    keywords: ["同じ", "型", "動き", "処理"],
    related: ["継承", "インターフェース", "メソッド"],
  },
];

export const LEVEL_ORDER: Level[] = ["初級", "中級", "上級"];

export const initialState: AppState = {
  learnedCount: {},
  weakTerms: {},
  favorites: {},
  history: [],
  attempts: 0,
  correct: 0,
  studyMinutes: 0,
  streak: 0,
  lastStudyDate: "",
  dailyQuizDoneDate: "",
  lang: "ja",
  fontScale: 1,
};
