import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#111827",
  },
  desktopWrap: {
    flex: 1,
    flexDirection: "row",
    gap: 16,
    padding: 14,
    justifyContent: "center",
  },
  desktopLeft: {
    flex: 1,
    maxWidth: 760,
    backgroundColor: "#f3f7fb",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8e0ea",
    overflow: "hidden",
  },
  desktopRight: {
    width: 420,
    backgroundColor: "#f3f7fb",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8e0ea",
    overflow: "hidden",
  },
  mainPanel: {
    flex: 1,
    backgroundColor: "#f3f7fb",
  },
  header: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: "#dce5ef",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: "#ffffff",
  },
  headerTitle: {
    color: "#0e5eab",
    fontSize: 18,
    fontWeight: "700",
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 12,
    paddingBottom: 18,
    gap: 10,
  },
  searchInput: {
    backgroundColor: "#e7f1f9",
    borderRadius: 11,
    paddingVertical: 10,
    paddingHorizontal: 12,
    color: "#1f2937",
  },
  panelCard: {
    backgroundColor: "#ffffff",
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#e3e8ef",
    padding: 12,
  },
  cardTitle: {
    color: "#0f223a",
    fontWeight: "700",
    fontSize: 15,
    marginBottom: 6,
  },
  cardTitleGap: {
    marginTop: 8,
  },
  bodyText: {
    color: "#4e6278",
    lineHeight: 20,
    fontSize: 13,
  },
  bulletText: {
    color: "#4e6278",
    lineHeight: 20,
    fontSize: 13,
  },
  levelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  levelBadge: {
    color: "#fff",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "700",
    overflow: "hidden",
  },
  levelText: {
    color: "#3f556d",
    fontSize: 13,
    flex: 1,
  },
  termRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e9f1",
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 8,
  },
  termIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  termTextWrap: {
    flex: 1,
  },
  termName: {
    color: "#0f223a",
    fontWeight: "700",
    fontSize: 14,
  },
  termSub: {
    color: "#62809c",
    fontSize: 12,
    marginTop: 2,
  },
  arrow: {
    color: "#9aa8b8",
    fontSize: 20,
  },
  progressBlock: {
    marginBottom: 14,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  progressName: {
    color: "#12253d",
    fontWeight: "700",
  },
  progressPercent: {
    color: "#1268b0",
    fontWeight: "700",
  },
  progressTrack: {
    height: 8,
    backgroundColor: "#dbe7f2",
    borderRadius: 999,
    overflow: "hidden",
    marginBottom: 5,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#1a73bc",
  },
  categoryListText: {
    color: "#6b8199",
    fontSize: 11,
    lineHeight: 17,
  },
  quizInput: {
    minHeight: 110,
    borderWidth: 1,
    borderColor: "#d0dbe8",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    textAlignVertical: "top",
    marginTop: 8,
    marginBottom: 10,
    backgroundColor: "#fff",
  },
  rowButtons: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: "#0f69b0",
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 12,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: "#e7eff8",
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#3e607f",
    fontWeight: "700",
    fontSize: 12,
  },
  ghostButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d4dfec",
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: "center",
  },
  ghostButtonText: {
    color: "#456887",
    fontWeight: "600",
    fontSize: 12,
  },
  scoreText: {
    color: "#0b5394",
    fontWeight: "700",
    marginTop: 4,
  },
  feedbackText: {
    color: "#304f6d",
    marginTop: 6,
    lineHeight: 20,
  },
  historyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f8fbff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e3eaf2",
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 6,
  },
  historyName: {
    color: "#1a2e45",
    fontWeight: "600",
  },
  detailPane: {
    flex: 1,
    backgroundColor: "#f3f7fb",
    padding: 12,
  },
  backText: {
    color: "#4a6581",
    marginBottom: 8,
  },
  detailTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailTitle: {
    color: "#10263f",
    fontWeight: "800",
    fontSize: 26,
  },
  detailSub: {
    color: "#65819d",
    marginTop: 2,
    marginBottom: 10,
    fontSize: 12,
  },
  detailCard: {
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#dfe7f0",
    padding: 10,
    marginBottom: 10,
  },
  detailCardTitle: {
    color: "#17324f",
    fontWeight: "700",
    marginBottom: 4,
    marginTop: 2,
  },
  levelToggleRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  langChip: {
    borderWidth: 1,
    borderColor: "#cbd8e6",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  langChipActive: {
    backgroundColor: "#0f69b0",
    borderColor: "#0f69b0",
  },
  langChipText: {
    color: "#5a7591",
    fontSize: 12,
    fontWeight: "600",
  },
  langChipTextActive: {
    color: "#fff",
  },
  relatedText: {
    color: "#4d6883",
    marginTop: 2,
  },
  bottomNav: {
    height: 56,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#dce4ee",
    flexDirection: "row",
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  navIcon: {
    marginBottom: 2,
  },
  navText: {
    color: "#6f8195",
    fontSize: 11,
  },
  navTextActive: {
    color: "#0f69b0",
    fontWeight: "700",
  },
});
